# Generated by Django 4.2.2 on 2023-07-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_trend',
            field=models.IntegerField(choices=[(0, 'Trend'), (1, 'Not trend')], default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default='-'),
        ),
    ]
