# Generated by Django 4.2.2 on 2023-07-31 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_order_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(default='-')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.order')),
            ],
            options={
                'db_table': 'order_comment',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
